[project]
name = "skbtools"
version = "0.1.0"
authors = [
    { name = "Unknown", email = "" }
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "matplotlib",
    "xarray",
    "gsw",
    "scipy",
    "ecco_v4_py",
    "cartopy",
    "basemap",
    "pandas",
    "numba",
    "pymap3d",
    "geopy",
    "certifi",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "pre-commit",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["GeigerMethod"]
include = ["*.py"]
